apiVersion: v1
kind: PersistentVolume
metadata:
  name: sloopstash-${ENVIRONMENT}-crm-app-log
spec:
  storageClassName: sloopstash-${ENVIRONMENT}-crm-app-log
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/sloopstash/${ENVIRONMENT}/crm/app/log
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
              - linux
 