apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sloopstash-${ENVIRONMENT}-crm-redis-data
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sloopstash-${ENVIRONMENT}-crm-redis-log
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer